import { Seat } from "./interface";

export const seat_data: Seat[] = [
  {
    seat_no: 1,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 2,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 3,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 4,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 5,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 6,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 7,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 8,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 9,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 10,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 11,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 12,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 13,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 14,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 15,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 16,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 17,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 18,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 19,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: false,
    last: true,
    reserve: false,
  },
  {
    seat_no: 20,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: false,
    single: false,
    window: false,
    last: true,
    reserve: false,
  },
  {
    seat_no: 21,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 22,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 23,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 24,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 25,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 26,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 27,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 28,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 29,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 30,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 31,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 32,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: false,
    last: false,
    reserve: false,
  },
  {
    seat_no: 33,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 34,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 35,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 36,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 37,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 38,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: true,
    window: true,
    last: false,
    reserve: false,
  },
  {
    seat_no: 39,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: false,
    last: true,
    reserve: false,
  },
  {
    seat_no: 40,
    passenger: { fname: "", lname: "", email: "" },
    date_booking: "",
    upper: true,
    single: false,
    window: false,
    last: true,
    reserve: false,
  },
];
